stages:
  - build
  - codestyle
  - tests

building:
  stage: build
  tags:
    - gitlab
  script:
    - apk add build-base findutils
    - find $CI_PROJECT_DIR -name "Makefile" -execdir make \;
  artifacts:
    paths:
      - $CI_PROJECT_DIR/src/C3_SimpleBashUtils-0/cat/s21_cat
      - $CI_PROJECT_DIR/src/C3_SimpleBashUtils-0/grep/s21_grep
    expire_in: 30 days

stylecheck:
  stage: codestyle
  tags:
    - gitlab
  script:
    - apk add --upgrade clang-extra-tools build-base findutils
    - output=$(clang-format -style="{$(grep ./materials/linters/.clang-format -e "BasedOnStyle")}" -n $(find $CI_PROJECT_DIR -name *.[ch])) 2>&1
    - if [ -n "$output" ]; then echo "$output" && return 2; fi

testing:
  stage: tests
  tags:
    - gitlab
  script:
    - apk add --upgrade clang-extra-tools build-base findutils
    - find $CI_PROJECT_DIR -name "Makefile" -execdir make check \;
