stages:
  - build

building:
  stage: build
  tags:
    - gitlab
  script:
    - apk add build-base
    - cd src/C3_SimpleBashUtils-0/cat 
    - make
    - cp ./s21_cat $CI_PROJECT_DIR/src/cat
    - cd ../grep
    - make
    - cp ./s21_grep $CI_PROJECT_DIR/src/grep
  artifacts:
    paths:
      - $CI_PROJECT_DIR/src/cat
      - $CI_PROJECT_DIR/src/grep
    expire_in: 30 days
