stages:
  - build
  - codestyle

building:
  stage: build
  tags:
    - gitlab
  script:
    - apk add build-base findutils
    - find $CI_PROJECT_DIR -name "Makefile" -execdir make \;
  artifacts:
    paths:
      - $CI_PROJECT_DIR/src/C3_SimpleBashUtils-0/cat/s21_cat
      - $CI_PROJECT_DIR/src/C3_SimpleBashUtils-0/grep/s21_grep
    expire_in: 30 days

stylecheck:
  stage: codestyle
  tags:
    - gitlab
  script:
    - apk add --upgrade clang-extra-tools build-base findutils
    - output=$(clang-format -style="{$(grep $CI_PROJECT_DIR BasedOnStyle)}" -n $(find $CI_PROJECT_DIR -name *.[ch]))
    - if [ -n "$output" ]; then echo "$output" && exit 1; fi

