stages:
  - build

building:
  stage: build
  tags:
    - part1
  script:
    - cd src/
    - bash script.sh
    - cd C3_SimpleBashUtils-0/src/cat
    - make
    - cd ../grep
    - make
  artifacts:
    paths:
      - src/build/cat
      - src/build/grep
    expire_in: 30 days